version: '3.7'

services:
    webapp:
        container_name: webapp
        build:
            context: .
            dockerfile: ./CyberLife/Dockerfile
        depends_on: [database]
        ports: ["5000:8090"]
    
    database:
        container_name: database
        image: postgres:12.13-alpine3.17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=Cyber
        ports: ["5555:5432"]